# .github/workflows/gcp-cloudrun-cicd.yml

name: GCP Cloud Run CI/CD

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      SERVICE_NAME: lychee-backend
      REGION: asia-southeast1
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      HOST: ${{ secrets.HOST }}
      IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/lychee-backend
      AI_LYCHEE_API_URL: ${{ secrets.AI_LYCHEE_API_URL }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: docker build -t $IMAGE .

      - name: Authenticate Docker for Artifact Registry
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev

      - name: Push Docker image
        run: docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --platform managed \
            --cpu 4 \
            --memory 16Gi \
            --concurrency 1 \
            --min-instances 1 \
            --max-instances 6 \
            --region $REGION \
            --allow-unauthenticated \
            --vpc-connector cloudrun-connector \
            --vpc-egress all \
            --set-env-vars JWT_SECRET=$JWT_SECRET,MONGO_URI=$MONGO_URI,HOST=$HOST,DATABASE_NAME=$DATABASE_NAME,AI_LYCHEE_API_URL=$AI_LYCHEE_API_URL,OPEN_AI_API_KEY=$OPEN_AI_API_KEY \
